#!/bin/bash

# Parameters
NTRIALS=$1
NWORKERS=$2
NCORES=$3
TIMES=$4

NTRIALS_PER_WORKER=$(( NTRIALS/NWORKERS ))

for (( i=1; i<=$TIMES; i++ ))
do
    echo "--- Start trial $i"
    # Prepare
    rm hpo_study_checkpoint_* logs/*
    ./study delete
    ./study create

    # Execution
    echo "--- Starting $NWORKERS worker, each worker runs on $NCORES cores and explores ${NTRIALS_PER_WORKER} trials"
    start=$SECONDS
    srun -N 1 -n ${NWORKERS} -c ${NCORES} --cpu-bind=verbose,cores --threads-per-core=1 --hint=nomultithread python main_optuna_db.py --trials ${NTRIALS_PER_WORKER} &> log.db.${NWORKERS}_${NCORES}_${i}
    end=$SECONDS
    echo "Duration: $((end-start)) seconds." >> log.db.${NWORKERS}_${NCORES}_${i}
    echo "--- End trial $i"
done
